Repository jnchaba/nacho-bot, pull requests merged in 2021-01, with the labels that each got.

#11 tft summoner name parser allows spaces
  nacho-bot/commands/tft.js
Labels: bug, enhancement

#15 Abstracted API methods used by tft.js into util file tftApi.js
  nacho-bot/commands/tft.js
  nacho-bot/scripts/tftApi.js
  nacho-bot/scripts/tftApiUtil.js
Labels: enhancement, refactor

#12 added lolwr calculations
  nacho-bot/commands/lol.js
  nacho-bot/commands/lolwr.js
  nacho-bot/commands/tft.js
  nacho-bot/nachobot.js
  nacho-bot/scripts/lolApiUtil.js
Labels: enhancement

#20 Riot icons
  nacho-bot/commands/lol.js
  nacho-bot/commands/tft.js
  nacho-bot/scripts/riotaccountUtil.js
Labels: enhancement, refactor

#19 added error for no args in eft, fixed errorUtil description to set de…
  nacho-bot/commands/eft.js
  nacho-bot/scripts/errorUtil.js
Labels: bug
